version: '3.9'
services:
  app:
    build: .
    container_name: ttf-fastapi
    ports:
      - "8000:8080"
    volumes:
      - /ttf-fastapi:/app
    command: "poetry run uvicorn app:app --port 8000 --host 0.0.0.0"

