apiVersion: v1
kind: Service
metadata:
  name: fastapi-sevice
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: fastapi
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fastapi
  sessionAffinity: None