apiVersion: apps/v1
kind: Deployment
metadata:
  name: take-the-food-fast-api
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: mittmannv8/take-the-food:latest
        imagePullPolicy: Always
        ports: 
        - containerPort: 80


